apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.autoUpdater.name }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.autoUpdater.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.autoUpdater.name }}
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io" 
  kind: ClusterRole
  name: {{ .Values.autoUpdater.name }}
