{{- if eq .Values.capabilities.autoupdate "enable" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.autoUpdater.name }}
  namespace: {{ .Values.ksNamespace }}
spec:
  schedule: {{ .Values.autoUpdater.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.autoUpdater.name }}
            image: {{ printf "%s:%s" .Values.autoUpdater.image.repository .Values.autoUpdater.image.tag  | quote }}
            imagePullPolicy: {{ .Values.autoUpdater.image.pullPolicy | quote }}
          restartPolicy: OnFailure
{{ end }}
